baseurl = "/"
languageCode = "en-us"
title = "Blog de Freddy"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Temas"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Palabras clave"
    url = "/tags/"
    weight = 3

[params]
    description = "Este blog fue hecho usando blogdown."
    footer = "&copy; [Freddy Hernández](https://fhernanb.github.io/) 2019 | [Github](https://github.com/fhernanb) | [Twitter](https://twitter.com/fhernanb74)"
